### ISSUE TITLE
Add open source software license

### ISSUE THREAD

**Issue by danielnazer** [mozilla-services/servicedenuages.fr#137]
This Mozilla repository has been identified as lacking a license. Consistent with Mozilla's [Licensing Policy](https://www.mozilla.org/en-US/MPL/license-policy/) an open source license should be applied to the code in this repository.

Please add an appropriate LICENSE.md file to the root directory of the project. In general, Mozilla's licensing policies are as follows:

-   Client-side products created by Mozilla employees or contributors should use the Mozilla Public License, Version 2.0 (MPL). 

-   Server-side products or utilities that support Mozilla products may use either the MPL or the Apache License 2.0 (Apache 2.0). 

In special cases, another license might be appropriate. If the repository is a fork of another repository it must apply the license of the original. Similarly, another license might be appropriate to match that of a broader project (for example Rust crates that Firefox depends on are published under an Apache 2.0 / MIT dual license, as that is the dual license used by the Rust programming language and projects).

Please ensure that any license added to the LICENSE.md file matches other licensing information in the repository (for example, it should match any license indicated in a setup.py or package.json file).

Mozilla staff can access more information in our Software Licensing Runbook – search for “Licensing Runbook” in Confluence to find it.

If you have any questions you can contact Daniel Nazer who can be reached at dnazer on Mozilla email or Slack.

OPENLIC-2023-01

**Comment by Natim** [comment]
@danielnazer This is a blog, we already asked if we could move it to @spiral-project to account for this kind of request.

**Comment by leplatrem** [comment]
This was discussed internally https://bugzilla.mozilla.org/show_bug.cgi?id=1782191 and transferring to another org is not as trivial as it seems if we want to be thorough with legal terms.
Daniel suggests we apply a `Apache 2.0` to the repo first.

If we can obtain a approval from the contributors, it would be even better :) 

- [x] @n1k0 
- [x] @glasserc 
- [x] @bnjbvr 
- [x] @almet 
- [x] @michielbdejong 
- [x] @phrawzty 
- [x] @adngdb 
- [ ] @Grahack 
- [ ] @oak11 
- [x] @magopian 
- [x] @elelay 
- [x] @leplatrem 
- [x] @Natim

**Comment by bnjbvr** [comment]
(Can't edit your comment, so just saying) I approve of this change.

**Comment by Natim** [comment]
I approve this change.

**Comment by n1k0** [comment]
wfm

**Comment by phrawzty** [comment]
I approve :)

(Also hi everybody! long time no see haha)

**Comment by michielbdejong** [comment]
Sure, go ahead!

**Comment by elelay** [comment]
I approve

**Comment by glasserc** [comment]
Fine with me!

**Comment by adngdb** [comment]
It's a yes! 

Also it's been forever since I last commented on a mozilla-related github issue, so… mandatory gif to celebrate. :heart: 

![](https://media.giphy.com/media/cWHzCmm1528Ks/giphy-downsized.gif)

**Comment by almet** [comment]
Works for me as well!

**Comment by magopian** [comment]
Works for me! Nice to see you all here ;)

**Comment by leplatrem** [comment]
Thanks everyone 🤗 

We have a vast majority, and the missing approvals concern these commits:
https://github.com/mozilla-services/servicedenuages.fr/commits?author=Grahack
https://github.com/mozilla-services/servicedenuages.fr/commits?author=oak11

Let's proceeed 🙏
