### ISSUE TITLE
Add a license information on each article.

### ISSUE THREAD

**Issue by almet** [mozilla-services/servicedenuages.fr#38]
Which licence should we use?

**Comment by leplatrem** [comment]
CC-0

**Comment by Natim** [comment]
CC-BY-NC

**Comment by almet** [comment]
"CC BY" pour moi, la clause NC me plait pas trop.

Je connais pas CC-0 ?

**Comment by phrawzty** [comment]
Je suis d'accord avec @ametaireau - la clause NC me semble un peu trop militant. Pourquoi pas CC-BY-SA comme juste milieu? :smiley:

**Comment by Natim** [comment]
Le SA c'est pas militant peut-être ?

**Comment by phrawzty** [comment]
CC-BY alors?

**Comment by almet** [comment]
Peut etre qu'ajouter un peu plus d'information sur mon choix peut etre utile:

> **Attribution (BY)**  Licensees may copy, distribute, display and perform the work and make derivative works based on it only if they give the author or licensor the credits in the manner specified by these.

Me semble necessaire parce que c'est la moindre des choses que de citer les auteurs;

> **Share-alike (SA)**  Licensees may distribute derivative works only under a license identical to the license that governs the original work. (See also copyleft.)

Discutable, mais en mon sens utile si on ne mets pas la clause NC: qui veut redistribuer peut, mais pas si il fait sauter la license (c'est surtout utile pour garder le BY)

> **Non-commercial (NC)**   Licensees may copy, distribute, display, and perform the work and make derivative works based on it only for noncommercial purposes.

Si l'objectif est de diffuser le plus largement le contenu, il me semble qu'il n'est pas necessaire d'avoir la clause _NC_. Si quelqu'un souhaite gagner de l'argent dans l'histoire, tant mieux pour cette personne, au contraire (ça peut etre utile pour de l'impression de documents par exemple)

**Comment by leplatrem** [comment]
CC-0 c'est bien aussi.

**Comment by almet** [comment]
Ca me semble effectivement pas mal du tout :) https://fr.wikipedia.org/wiki/Licence_CC0

**Comment by phrawzty** [comment]
Perso, je crois absolument dans l'utilité et intérêt public d'une licence virale (c'est-à-dire la clause « SA » dans le cas au-dessus). Mais bon, si le groupe est content du fait que le CC-0 implique la possibilité de closed-source, je ne lutterai pas contre. :neutral_face:

**Comment by almet** [comment]
Effectivement, j'avais lu trop rapidement:

> par exemple, il n’y a pas besoin de citer l’auteur (sauf si la loi du pays l’exige, c’est par exemple le cas en France) ou de redistribuer/modifier l'œuvre sous la même licence.

/me backoffs to CC-BY

**Comment by Natim** [comment]
Can we all agree on `CC-BY` ?

**Comment by phrawzty** [comment]
> Can we all agree on CC-BY ?

:+1:

**Comment by n1k0** [comment]
+1

**Comment by almet** [comment]
+1

> On Oct 12 2015, at 3:52 pm, Nicolas Perriault
