### ISSUE TITLE
Write an article about Web Crypto and how to use it for signing.

### ISSUE THREAD

**Issue by almet** [mozilla-services/servicedenuages.fr#60]
It might make sense to create an article about how to use Web Crypto + Kinto. This is related to what @michielbdejong has in mind, I believe, but for the signature of the records rather than the encryption.

That could make two great articles!

**Comment by michielbdejong** [comment]
Right, that reminds me, the new way to set RemoteTransformers (as collection-level options) landed this morning, so I can write my blogpost about it now about how we use this in the gaia Sync app. :)

**Comment by almet** [comment]
Yep, that makes a lot of sense :)
